"use client"
import './globals.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import { Geist, Geist_Mono } from 'next/font/google';
import React, { useEffect, useState } from 'react';
import Script from 'next/script';
import axios from 'axios';

const geistSans = Geist({ subsets: ['latin'], variable: '--font-geist-sans' });
const geistMono = Geist_Mono({ subsets: ['latin'], variable: '--font-geist-mono' });

const metadata = {
  title: 'synaptix-labs',
  description: 'Generated by synaptix-labs'
};





export default function RootLayout({ children }) {
 

  useEffect(() => {
    const fetchTags = async () => {
      try {
        const response = await axios.get('/api/customTag');
      
            const head = document.head;
            const body = document.body;
        
            // Helper function to safely create and insert a script tag
            function insertHTML(position, container, html) {
                if (!html) return;
                const temp = document.createElement('div');
                temp.innerHTML = html;
                const node = temp.firstChild;
                if (position === 'start') {
                    container.insertBefore(node, container.firstChild);
                } else {
                    container.appendChild(node);
                }
            }
        
            // Inject into HEAD
            response.data?.data?.head?.forEach(tag => {
                const pos = tag.position === 'start' ? 'start' : 'end';
                insertHTML(pos, head, tag.text);
            });
        
            // Inject into BODY
            response.data?.data?.body?.forEach(tag => {
                const pos = tag.position === 'start' ? 'start' : 'end';
                insertHTML(pos, body, tag.text);
            });

      } catch (error) {
        console.error("Error fetching custom tags:", error);
      }
    };
    fetchTags();
  }, []);





  return (
    <html lang="en">
      <head>
        <title>synaptix-labs</title>
        <link rel="icon" href="/favicon.png" />
        <link rel="stylesheet" href="/fonts/stylesheet.css" />
        
        

        <Script src="https://cdn.userway.org/widget.js" data-account="lI863fd1ND"></Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased !bg-[#070D1F]`}>
        {children}
      </body>
    </html>
  );
}